# GoReleaser configuration file.
#
# For more info, browse to http://goreleaser.com.
#
# NOTE: The GoReleaser is not meant to be run directly, but rather through
# Make's release-build target.

project_name: Oasis Rosetta Gateway

env:
  # Require use of Go modules.
  - GO111MODULE=on

builds:
  - id: oasis-rosetta-gateway
    binary: oasis-rosetta-gateway
    flags:
      - -trimpath
    ldflags:
      # NOTE: At the moment, GoReleaser produces different binaries when
      # releases are built from different git paths, unless -buildid= is added
      # to ldflags.
      # For more details, see: https://github.com/oasislabs/goreleaser/issues/1.
      - -buildid=
      - "{{.Env.GOLDFLAGS_VERSION}}"
    goos:
      - linux
    goarch:
      - amd64

archives:
  - name_template: "{{replace .ProjectName \" \" \"_\" | tolower}}_{{.Version}}_{{.Os}}_{{.Arch}}"
    wrap_in_directory: true
    files:
      - CHANGELOG.md
      - README.md
      - LICENSE

checksum:
  name_template: SHA256SUMS-{{.Version}}.txt
  algorithm: sha256

snapshot:
  name_template: "{{.Version}}-dev"

release:
  name_template: "{{.ProjectName}} {{.Version}}"
